name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt upgrade -y
        sudo apt install -y aria2
        sudo apt remove -y cmake
        sudo apt install -y apt-transport-https ca-certificates gnupg software-properties-common wget
        wget -O - https://apt.kitware.com/keys/kitware-archive-latest.asc | sudo apt-key add -
        sudo apt-add-repository 'deb https://apt.kitware.com/ubuntu/ focal main'
        sudo apt update
        sudo apt install -y cmake

    - name: Install LLVM
      run: sudo bash -c "$(wget -O - https://apt.llvm.org/llvm.sh)"
    
    - name: Set up Android NDK r23b
      run: | 
        aria2c -o android-ndk-r23b-linux.zip https://dl.google.com/android/repository/android-ndk-r23b-linux.zip
        unzip -q -d ~ android-ndk-r23b-linux.zip
      
    - name: Build
      run: |
        mkdir build
        cd build
        cmake ..
        make

    - name: Set outputs
      id: vars
      run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: Wrapper.x86_64.${{ steps.vars.outputs.sha_short }}
        include-hidden-files: true
        path: |
          rootfs
          wrapper
          Dockerfile

    - name: Create Release Zip File
      run: zip -r Wrapper.x86_64.${{ steps.vars.outputs.sha_short }}.zip rootfs/ wrapper Dockerfile
      
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        files: Wrapper.x86_64.${{ steps.vars.outputs.sha_short }}.zip
        body: ${{ github.event.head_commit.message }}
        prerelease: true
        name: Wrapper.x86_64.${{ steps.vars.outputs.sha_short }}
        tag_name: Wrapper.x86_64.${{ steps.vars.outputs.sha_short }}
        